name: dart_algorithms
description: Data structures and algorithms with Dart.
# version: 0.1.0
homepage: https://github.com/jarontai/dart-algorithms
author: jarontai <jaroncn@gmail.com>
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  test: ^1.0.0
